name: prod-deploy-actions

on:
  push:
    branches: [ "dev" ]

jobs:
  build-and-push-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # AWS 자격 증명 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      # ECR 로그인
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Docker 빌드 & 푸시
      - name: Build and Push Docker Image
        run: |
          IMAGE_URI="${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY_FRONTEND }}:latest"
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-push-ecr
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1) ECR 로그인
            aws ecr get-login-password --region ap-northeast-2 \
              | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}

            # 2) docker-compose pull & up
            cd /home/ubuntu/MVP_back
            docker compose pull
            docker compose up -d